name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest

      - name: Build and push Menu Service image
        uses: docker/build-push-action@v4
        with:
          context: ./menu-service
          file: ./menu-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/menu-service:latest

      - name: Build and push Order Service image
        uses: docker/build-push-action@v4
        with:
          context: ./order-service
          file: ./order-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest

      - name: Build and push Payment Service image
        uses: docker/build-push-action@v4
        with:
          context: ./payment-service
          file: ./payment-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest

      - name: Build and push Inventory Service image
        uses: docker/build-push-action@v4
        with:
          context: ./inventory-service
          file: ./inventory-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest

      - name: Build and push Customer Service image
        uses: docker/build-push-action@v4
        with:
          context: ./customer-service
          file: ./customer-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:latest
